# This file contains configuration flags to customize my site
# theme: jekyll-theme-minimal
remote_theme: yaoyao-liu/minimal-light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Basic Information 
name: "Annetta's blog"
description: ""
title: Annetta 
# position: Ph.D. Student
# affiliation: Your Affiliation
email: annetta@berkeley.edu
linkedin: https://www.linkedin.com/in/junwen-zheng-789569195/
github_link: https://annetta-zheng.github.io


google_analytics: G-1WEYSPQBEB
# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: portfolio page
description: github personal blog repo portfolio page


# Gitalk
gitalk:
  clientID: db979e7bf4ef0e309806
  clientSecret: 00e30f039a0c0b46ceafcb9d55d397e2d23d9d59
  repo: annetta-zheng.github.io
  owner: annetta-zheng
  
  
# The following files will be removed from the generated website.
exclude:
  - README.md
  - LICENSE
