# This file contains configuration flags to customize my site
# theme: jekyll-theme-minimal
website: https://annetta-zheng.github.io/project-list

remote_theme: yaoyao-liu/minimal-light
plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc
  # - jekyll-last-modified-at
  # - jekyll-spaceship

# Basic Information 
name: "Annetta's blog"
description: ""
title: Annetta's Website
github: annetta-zheng
# position: Ph.D. Student
# affiliation: Your Affiliation
email: annetta@berkeley.edu
linkedin: https://www.linkedin.com/in/annetta-zheng-789569195/
github_link: https://github.com/annetta-zheng/annetta-zheng.github.io

# toc: true
last-modified-at:
    date-format: '%d-%b-%y'

google_analytics: G-1WEYSPQBEB
# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: portfolio page
description: github personal blog repo portfolio page

favicon: ./img/favicon.png

toc: true
# toc:
#   no_toc_section_class: exclude # default: no_toc_section

# Gitalk
gitalk:
  clientID: db979e7bf4ef0e309806
  clientSecret: 00e30f039a0c0b46ceafcb9d55d397e2d23d9d59
  repo: annetta-zheng.github.io
  owner: annetta-zheng


collections:
  tags:
    output: true
    permalink: tags/:title/
  posts:
    output: true
    permalink: "blog/:categories/:title"

defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag


include: [_pages, _node_modules]

# The following files will be removed from the generated website.
exclude:
  - README.md
  - LICENSE
  - v1.md
  - _archive

